// This file acts as a scalable registry for your manual SEO pages.
// To add a new manual page:
// 1. Create the folder app/blogs/your-new-slug/page.jsx
// 2. Add the metadata object to this array below.

export const manualBlogs = [
  // NEW GSC-LED SEO GROWTH PAGES — 2026-08-29
  {
    id: "best-marketing-agency-in-egypt/branding-agency-egypt/brand-identity-design-agency-egypt",
    title: "Brand Identity Design Agency Egypt 2026: Buyer Guide",
    description: "Compare brand identity agencies in Egypt by strategy, bilingual identity systems, guidelines, handover and rollout before hiring.",
    image: "/blogs/brand-identity-design-agency-egypt-2026.webp",
    date: "2026-08-29",
    tags: ["Brand Identity", "Branding", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/branding-agency-egypt/branding-agency-cairo",
    title: "Branding Agency Cairo 2026: Services & Selection",
    description: "Compare branding agencies in Cairo and New Cairo by strategy, identity, local collaboration, bilingual execution and rollout.",
    image: "/blogs/branding-agency-cairo-2026.webp",
    date: "2026-08-29",
    tags: ["Branding", "Cairo", "Local SEO"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/branding-agency-egypt/logo-design-price-egypt",
    title: "Logo Design Price Egypt 2026: Cost & Deliverables",
    description: "Compare logo design prices in Egypt using published provider examples, deliverables, source files and the difference between logo and identity.",
    image: "/blogs/logo-design-price-egypt-2026.webp",
    date: "2026-08-29",
    tags: ["Logo Design", "Pricing", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "digital-marketing-agency-egypt",
    title: "Digital Marketing Agency Egypt 2026: Buyer Guide",
    description: "Compare digital marketing agencies in Egypt by services, strategy, measurement, team, lead quality and commercial fit.",
    image: "/blogs/digital-marketing-agency-egypt-2026.webp",
    date: "2026-08-29",
    tags: ["Digital Marketing", "Agency", "Egypt"],
    isManual: true,
    isPillar: true,
  },
  {
    id: "digital-marketing-agency-egypt/digital-marketing-services-egypt",
    title: "Digital Marketing Service Mix Egypt 2026: What to Prioritize",
    description: "Choose which digital marketing services to prioritize across SEO, paid media, social, content, websites, tracking and CRO.",
    image: "/blogs/digital-marketing-services-egypt-2026.webp",
    date: "2026-08-29",
    tags: ["Digital Marketing", "Services", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "digital-marketing-agency-egypt/digital-marketing-agency-cairo",
    title: "Digital Marketing Agency Cairo 2026: Local Buyer Guide",
    description: "Compare digital marketing agencies in Cairo by local collaboration, SEO, paid media, social, tracking and lead generation.",
    image: "/blogs/digital-marketing-agency-cairo-2026.webp",
    date: "2026-08-29",
    tags: ["Digital Marketing", "Cairo", "Lead Generation"],
    isManual: true,
    isPillar: false,
  },

  // NEW GSC-LED COMMERCIAL CLUSTERS — 2026-08-26
  {
    id: "best-marketing-agency-in-egypt/branding-agency-egypt/branding-prices-egypt",
    title: "Branding Prices in Egypt 2026: Cost & Scope Guide",
    description: "Compare branding prices in Egypt by scope, strategy, naming, identity, guidelines, rollout and agency model before requesting a quote.",
    image: "/blogs/branding-agency-egypt.jpg",
    date: "2026-08-26",
    tags: ["Branding", "Pricing", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/branding-agency-egypt/brand-naming-agency-egypt",
    title: "Brand Naming Agency Egypt 2026: Naming Process Guide",
    description: "Choose a brand naming agency in Egypt using a practical process for strategy, Arabic-English checks, screening, shortlisting and trademark handoff.",
    image: "/blogs/branding-agency-egypt.jpg",
    date: "2026-08-26",
    tags: ["Branding", "Naming", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/branding-agency-egypt/corporate-branding-services-egypt",
    title: "Corporate Branding Services Egypt 2026: Buyer Guide",
    description: "Compare corporate branding services in Egypt by strategy, architecture, bilingual identity, guidelines, templates, rollout and governance.",
    image: "/blogs/branding-agency-egypt.jpg",
    date: "2026-08-26",
    tags: ["Branding", "Corporate Branding", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/seo-agency-egypt/seo-cost-egypt",
    title: "SEO Cost in Egypt 2026: Pricing & Retainer Guide",
    description: "Compare SEO cost in Egypt by technical work, content, local SEO, authority, reporting and competition before choosing a monthly retainer.",
    image: "/blogs/seo-agency-egypt.jpg",
    date: "2026-08-26",
    tags: ["SEO", "Pricing", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/seo-agency-egypt/local-seo-services-egypt",
    title: "Local SEO Services Egypt 2026: Maps & Leads Guide",
    description: "Build local SEO in Egypt with Google Business Profile, location pages, reviews, local content, technical SEO and conversion tracking.",
    image: "/blogs/seo-agency-egypt.jpg",
    date: "2026-08-29",
    tags: ["SEO", "Local SEO", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/seo-agency-egypt/seo-for-real-estate-egypt",
    title: "SEO for Real Estate Egypt 2026: Leads & Rankings Guide",
    description: "Use SEO for real estate in Egypt to rank project, location and buyer-intent pages with technical SEO, topic clusters and lead tracking.",
    image: "/blogs/seo-agency-egypt.jpg",
    date: "2026-08-26",
    tags: ["SEO", "Real Estate", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/real-estate-marketing-egypt/real-estate-lead-generation-egypt",
    title: "Real Estate Lead Generation Egypt 2026: Funnel Guide",
    description: "Improve real estate lead generation in Egypt with channel strategy, landing pages, qualification, CRM follow-up and lead-quality reporting.",
    image: "/blogs/real-estate-marketing-egypt.jpg",
    date: "2026-08-29",
    tags: ["Real Estate", "Lead Generation", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/social-media-agency/social-media-management-companies-egypt",
    title: "Social Media Management Companies Egypt 2026: Guide",
    description: "Compare social media management companies in Egypt by strategy, content, community, approvals, reporting, account ownership and lead support.",
    image: "/blogs/social-media-agency.jpg",
    date: "2026-08-29",
    tags: ["Social Media", "Management", "Egypt"],
    isManual: true,
    isPillar: false,
  },

  {
    id: "best-marketing-agency-in-egypt/social-media-packages-egypt",
    title: "Social Media Packages Egypt 2026: Pricing & Deliverables",
    description:
      "Compare social media packages in Egypt by strategy, content, video, community, paid media, reporting, revisions, and hidden costs.",
    image: "/blogs/social-media-packages-egypt.png",
    date: "2026-08-26",
    tags: ["Social Media", "Pricing", "Packages", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  // PILLAR PAGE
  {
    id: "best-marketing-agency-in-egypt",
    title: "Best Marketing Agency in Egypt 2026: Comparison Guide",
    description:
      "Compare marketing agencies in Egypt by strategy, SEO, paid media, social, content, reporting, pricing model, and commercial fit.",
    image: "/blogs/best-marketing-agency.png",
    date: "2026-08-29",
    tags: ["SEO", "Digital Marketing", "Agency", "Growth"],
    isManual: true,
    isPillar: true,
  },

  // CLUSTER PAGES (under best-marketing-agency-in-egypt)
  {
    id: "best-marketing-agency-in-egypt/seo-agency-egypt",
    title: "Best SEO Agency in Egypt 2026: How to Choose",
    description:
      "Compare SEO agencies in Egypt by technical SEO, query strategy, content, local SEO, authority, reporting, pricing model, and execution quality.",
    image: "/blogs/seo-agency-egypt.jpg",
    date: "2026-08-26",
    tags: ["SEO", "Agency", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/social-media-agency",
    title: "Best Social Media Agency in Egypt 2026: Selection Guide",
    description:
      "Compare social media agencies in Egypt by strategy, content, community, paid media, reporting, platform fit, and lead generation.",
    image: "/blogs/social-media-agency.jpg",
    date: "2026-08-29",
    tags: ["Social Media", "Agency", "Egypt"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/performance-marketing",
    title: "Best Performance Marketing Agencies Egypt 2026: Compare",
    description:
      "Compare performance marketing agencies in Egypt by tracking, Google Ads, Meta Ads, creative testing, CRO, lead quality, reporting, and pricing.",
    image: "/blogs/performance-marketing.jpg",
    date: "2026-08-29",
    tags: ["Performance Marketing", "Google Ads", "Meta Ads"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/content-strategy-agency",
    title: "Best Content Strategy Agency Egypt 2026",
    description:
      "Discover top content strategy agencies in Egypt for 2026. Expert content planning, SEO content, and brand storytelling services.",
    image: "/blogs/content-strategy-agency.jpg",
    date: "2026-08-29",
    tags: ["Content Strategy", "Content Marketing", "Agency"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/web-development-agency",
    title: "Best Web Development Agency Egypt 2026",
    description:
      "Find the best web development agency in Egypt for 2026. Expert website design, e-commerce, and custom development services.",
    image: "/blogs/web-development-agency.jpg",
    date: "2026-08-29",
    tags: ["Web Development", "Website Design", "E-commerce"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/real-estate-marketing-egypt",
    title: "Real Estate Marketing Agency Egypt 2026: Lead Generation Guide",
    description:
      "Choose a real estate marketing agency in Egypt using a practical framework for lead quality, paid media, SEO, content, tracking, and sales handoff.",
    image: "/blogs/real-estate-marketing-egypt.jpg",
    date: "2026-08-29",
    tags: ["Real Estate", "Property Marketing", "Lead Generation"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/branding-agency-egypt",
    title: "Best Branding Agency in Egypt 2026: Comparison Guide",
    description:
      "Compare branding agencies in Egypt by strategy, naming, identity, bilingual systems, rollout, pricing factors, and business fit.",
    image: "/blogs/branding-agency-egypt.jpg",
    date: "2026-08-29",
    tags: ["Branding", "Brand Identity", "Logo Design"],
    isManual: true,
    isPillar: false,
  },
  {
    id: "best-marketing-agency-in-egypt/content-creation-agency-egypt",
    title: "Content Creation Agency Egypt 2026: Services Guide",
    description:
      "Compare content creation agencies in Egypt for video, social content, design, copy, production, repurposing, workflow, and pricing factors.",
    image: "/blogs/content-creation-egypt.jpg",
    date: "2026-08-26",
    tags: ["Content Creation", "Video Production", "Photography"],
    isManual: true,
    isPillar: false,
  },

  // STANDALONE BLOGS - MARKETING
  {
    id: "digital-marketing-pricing-egypt",
    title: "Digital Marketing Pricing Egypt 2026: Complete Cost Guide",
    description:
      "Complete pricing guide for digital marketing services in Egypt 2026. Compare costs for SEO, Google Ads, social media, web development from top agencies.",
    image: "/blogs/digital-marketing-pricing-egypt.jpg",
    date: "2026-08-29",
    tags: ["Pricing", "Budget", "Cost Guide", "Digital Marketing"],
    isManual: true,
    isPillar: false,
    isStandalone: true,
  },
];
